name: Docker Image CI

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
      name: Build Docker image
      runs-on: self-hosted
      steps:
        - name: Set BRANCH
          run: echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV

        - name: Login to Docker Hub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        - name: Checkout project
          uses: actions/checkout@v3.5.0

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2.1.0

        - name: Setup Docker buildx action
          uses: docker/setup-buildx-action@v2.5.0

        - name: Run Docker buildx
          run: |
            docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ${{ secrets.DOCKER_HUB_USER }}/monero-lws-admin:$BRANCH \
            --push .


